version: "3"
services:
    n2n_proxy_nat:
      image: zctmdc/n2n_proxy:latest
      restart: always
      privileged: true
      environment:
        - MODE=DHCPD
        - STATIC_IP=10.10.0.1
        - N2N_GROUP=zctmdc_proxy
        - N2N_PASS=zctmdc_proxy
        - N2N_SERVER=n2n.lucktu.com:10086
        - N2N_NAT=TRUE
        - N2N_ARGS=-Av
      # volumes:
      #   - dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
