version: "3"
services:
  n2n_proxy_nat_lucktu:
    build:
      context: ../n2n_proxy
      dockerfile: Dockerfile
    image: zctmdc/n2n_proxy:Alpha
    restart: always
    privileged: true
    environment:
      - MODE=DHCPD
      - N2N_IP=10.0.10.1
      - N2N_COMMUNITY=zctmdc_proxy
      - N2N_KEY=zctmdc_proxy
      - N2N_SERVER=n2n.lucktu.com:10086
      - N2N_ARGS=-Avr
      - N2N_NAT=TRUE
      - N2N_PROXY=TRUE
      - N2N_ROUTE=FALSE
      - PROXY_ARGS=-L=:1080
    ports:
      - 14080:1080
    # volumes:
    #   - ./dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    command: ["/bin/bash", "-c", "/usr/local/sbin/run.sh"]
  n2n_proxy_nat_fast:
    build:
      context: ../n2n_proxy
      dockerfile: Dockerfile
    image: zctmdc/n2n_proxy:Alpha
    restart: always
    privileged: true
    environment:
      - MODE=DHCPD
      - N2N_IP=10.20.30.1
      - N2N_COMMUNITY=proxy_fast
      - N2N_KEY=n2n_fast
      - N2N_SERVER=t0.lucktu.com:10086
      - N2N_ARGS=-Avr
      - N2N_NAT=TRUE
      - N2N_PROXY=TRUE
      - N2N_ROUTE=FALSE
      - PROXY_ARGS=-L=:1080
    ports:
      - 11080:1080
    # volumes:
    #   - ./dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    command: ["/bin/bash", "-c", "/usr/local/sbin/run.sh"]
