version: "3"
services:
  n2n_supernode:
    image: zctmdc/n2n_ntop:Alpha
    restart: always
    privileged: true
    ports:
      - 10086:10086/udp
    environment:
      - MODE=SUPERNODE
      - N2N_PORT=10086
      - N2N_ARGS=-v
    command: ["/bin/bash", "-c", "/usr/local/sbin/run.sh"]

  n2n_edge_dhcpd:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - n2n_supernode
    image: zctmdc/n2n_ntop:Alpha
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=DHCPD
      - N2N_PORT=10086
      - N2N_TUN=edge_dhcpd
      - N2N_IP=10.10.10.1
      - N2N_COMMUNITY=n2n
      - N2N_KEY=test
      - N2N_SERVER=n2n.lucktu.com:10086
      - N2N_ARGS=-A -v
    # volumes:
    #   - ./dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    command: ["/bin/bash", "-c", "/usr/local/sbin/run.sh"]

  n2n_edge_dhcp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - n2n_edge_dhcpd
      - n2n_supernode
    image: zctmdc/n2n_ntop:Alpha
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=DHCP
      - N2N_PORT=10086
      - N2N_TUN=edge_dhcp
      - N2N_COMMUNITY=n2n
      - N2N_KEY=test
      - N2N_SERVER=n2n.lucktu.com:10086
      - N2N_ARGS=-A -vr
    command: ["/bin/bash", "-c", "/usr/local/sbin/run.sh"]

  n2n_edge_static:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - n2n_edge_dhcpd
      - n2n_supernode
    image: zctmdc/n2n_ntop:Alpha
    restart: always
    privileged: true
    # network_mode: host
    environment:
      - MODE=STATIC
      - N2N_PORT=10086
      - N2N_TUN=edge_static
      - N2N_IP=10.10.10.100
      - N2N_COMMUNITY=n2n
      - N2N_KEY=test
      - N2N_SERVER=n2n.lucktu.com:10086
      - N2N_ARGS=-A -v
    command: ["/bin/bash", "-c", "/usr/local/sbin/run.sh"]
