version: "3"
services:
  n2n_ntop:
    build:
      context: n2n_ntop
      dockerfile: Dockerfile
    image: zctmdc/n2n_ntop:Alpha

  n2n_proxy:
    build:
      context: n2n_proxy
      dockerfile: Dockerfile
    image: zctmdc/n2n_proxy:Alpha

  file-server:
    build:
      context: nginx_file_server
      dockerfile: Dockerfile
    image: zctmdc/file-server:Alpha

  easy_explore:
    build:
      context: easy-explorer
      dockerfile: Dockerfile
    image: zctmdc/easy-explorer:Alpha

  easy-explorer-smb:
    build:
      context: easy-explorer-smb
      dockerfile: Dockerfile
    image: zctmdc/easy-explorer-smb:Alpha
