version: "3"
services:
    n2n_proxy_gw_static:
      image: zctmdc/n2n-proxy:latest
      restart: always
      privileged: true
      environment:
        - MODE=STATIC
        - N2N_IP=10.0.10.20
        - N2N_COMMUNITY=zctmdc-proxy
        - N2N_KEY=zctmdc-proxy
        - N2N_SERVER=n2n.lucktu.com:10086
        - N2N_ROUTE=TURE
        - N2N_DESTINATION=192.168.0.0/16
        - N2N_GATEWAY=10.0.10.1
        - N2N_ARGS=-Av
        - N2N_PROXY=TRUE
      # volumes:
      #   - ../n2n_ntop/edge-dhcp-server/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      ports:
        - 10080:1080
      command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
