version: "3"
services:
    n2n_proxy_gw_dhcp:
      image: zctmdc/n2n-proxy:latest
      restart: always
      privileged: true
      environment:
        - MODE=DHCP
        - N2N_COMMUNITY=zctmdc-proxy
        - N2N_KEY=zctmdc-proxy
        - N2N_SERVER=n2n.lucktu.com:10086
        - N2N_ROUTE=TURE
        - N2N_DESTINATION=192.168.0.0/16
        - N2N_GATEWAY=10.0.10.1
        - N2N_ARGS=-Avr
        - N2N_PROXY=TRUE
        - PROXY_ARGS=-L=:1080
      volumes:
        - ../n2n_ntop/edge-dhcp-server/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      ports:
        - 1080:1080
      command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
