version: "3"
services:
  n2n_supernode:
    image: zctmdc/n2n-vpn:latest
    restart: always
    privileged: true
    ports:
      - 10086:10086/udp
    environment:
      - MODE=SUPERNODE
      - N2N_PORT=10086
    command: ["/bin/bash","-c","/usr/local/sbin/run.sh"]