version: "3"
services:
    n2n_proxy_nat:
      image: zctmdc/n2n_proxy:latest
      restart: always
      privileged: true
      environment:
        - MODE=DHCPD
        - STATIC_IP=10.0.0.1
        - N2N_GROUP=zctmdc_dhcp
        - N2N_PASS=zctmdc_dhcp
        - N2N_SERVER=n2n.lucktu.com:10086
        - N2N_NAT=TRUE
      volumes:
        - dhcpd.conf:/etc/dhcp/dhcpd.conf
      command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]

    n2n_proxy_nat:
      image: zctmdc/n2n_proxy:latest
      restart: always
      privileged: true
      environment:
        - MODE=DHCP
        - N2N_GROUP=zctmdc_dhcp
        - N2N_PASS=zctmdc_dhcp
        - N2N_SERVER=n2n.lucktu.com:10086
        - N2N_GW=TURE
        - N2N_DESTINATION=192.168.0.0/16
        - N2N_GATEWAY=10.0.0.1
      volumes:
        - dhcpd.conf:/etc/dhcp/dhcpd.conf
      ports:
        - 1080:1080
      command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]

    n2n_proxy_nat:
      image: zctmdc/n2n_proxy:latest
      restart: always
      privileged: true
      environment:
        - MODE=STATIC
        - STATIC_IP=10.0.0.20
        - N2N_GROUP=zctmdc_dhcp
        - N2N_PASS=zctmdc_dhcp
        - N2N_SERVER=n2n.lucktu.com:10086
        - N2N_GW=TURE
        - N2N_DESTINATION=192.168.0.0/16
        - N2N_GATEWAY=10.0.0.2
      volumes:
        - ../n2n_ntop/edge-dhcp-server/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      ports:
        - 1080:1080
      command: ["/bin/sh","-c","/usr/local/sbin/run.sh"]
